// London street art spots and walking tours.
// Street art changes constantly: walls get repainted, pieces get buffed.
// Coordinates point to the wall / street, not to a single guaranteed piece.
window.SPOTS = [
  {
    id: 'leake-street',
    name: 'Leake Street Graffiti Tunnel',
    area: 'Waterloo',
    lat: 51.5019, lng: -0.1145,
    tags: ['legal wall', 'tunnel'],
    blurb: "You're at Leake Street, the 300 metre tunnel under Waterloo station. Banksy launched it as a legal graffiti space with his Cans Festival in 2008, and the walls are repainted almost daily. If you see someone painting, stop and watch: it's one of the few places in London where it's allowed.",
  },
  {
    id: 'undercroft',
    name: 'Southbank Undercroft',
    area: 'South Bank',
    lat: 51.5068, lng: -0.1167,
    tags: ['skate spot', 'tags'],
    blurb: "This is the Southbank Undercroft, under the Queen Elizabeth Hall. Skaters have used it since the 1970s, and its layered tags and throw-ups were saved from redevelopment by a long public campaign in 2014.",
  },
  {
    id: 'brick-lane',
    name: 'Brick Lane',
    area: 'Shoreditch & Spitalfields',
    lat: 51.5218, lng: -0.0718,
    tags: ['murals', 'paste-ups'],
    blurb: "Welcome to Brick Lane, the heart of East London street art. Look up as well as along: big murals cover the side walls, and the shutters, doorways and drainpipes hide paste-ups, stencils and small sculptures.",
  },
  {
    id: 'hanbury-street',
    name: 'Hanbury Street',
    area: 'Shoreditch & Spitalfields',
    lat: 51.5205, lng: -0.0705,
    tags: ['murals'],
    blurb: "Hanbury Street, just off Brick Lane, is home to some of the area's largest murals. The Belgian artist ROA painted his famous giant crane bird here in 2010, which helped put this street on the map.",
  },
  {
    id: 'redchurch',
    name: 'Redchurch & Ebor Street',
    area: 'Shoreditch',
    lat: 51.5240, lng: -0.0745,
    tags: ['murals', 'stencils'],
    blurb: "Redchurch Street and the lanes around Ebor Street. The side walls and car parks here rotate big commissioned pieces, while the alleys are full of stickers and stencils.",
  },
  {
    id: 'village-underground',
    name: 'Village Underground Wall',
    area: 'Shoreditch',
    lat: 51.5245, lng: -0.0786,
    tags: ['rotating wall'],
    blurb: "This is the Village Underground wall on Holywell Lane. Look for the old tube carriages on the roof above. The giant wall below gets a new piece every few months, often from internationally known artists.",
  },
  {
    id: 'rivington',
    name: 'Rivington Street',
    area: 'Shoreditch',
    lat: 51.5260, lng: -0.0800,
    tags: ['murals', 'history'],
    blurb: "Rivington Street, one of the original Shoreditch street art streets. Banksy, Eine and many others have painted around here since the early 2000s, and the walls and shutters still change constantly.",
  },
  {
    id: 'whitecross',
    name: 'Whitecross Street',
    area: 'Islington',
    lat: 51.5233, lng: -0.0935,
    tags: ['murals', 'market'],
    blurb: "Whitecross Street, home of a weekday food market and the Whitecross Street Party, which has filled these walls with colourful murals for years.",
  },
  {
    id: 'shop-until-you-drop',
    name: 'Banksy, "Shop Until You Drop"',
    area: 'Mayfair',
    lat: 51.5101, lng: -0.1436,
    tags: ['Banksy'],
    blurb: "Look up at the corner of Bruton Lane. That's Banksy's Shop Until You Drop from 2011, a woman falling from a building, still clutching her shopping trolley. It's one of the few Banksy pieces left in central London.",
  },
  {
    id: 'amy-winehouse',
    name: 'Amy Winehouse Mural',
    area: 'Camden',
    lat: 51.5370, lng: -0.1405,
    tags: ['portrait', 'tribute'],
    blurb: "This is Pegasus's tribute to Amy Winehouse on Bayham Street, just round the corner from the Camden pubs and venues she loved.",
  },
  {
    id: 'camden-lock',
    name: 'Camden Market & Lock',
    area: 'Camden',
    lat: 51.5414, lng: -0.1460,
    tags: ['murals', 'shopfronts'],
    blurb: "Camden Market and the lock. Look out for the giant 3D shop-front sculptures on the High Street and the painted walls along the canal towpath.",
  },
  {
    id: 'hackney-wick',
    name: 'Hackney Wick & Fish Island',
    area: 'Hackney Wick',
    lat: 51.5435, lng: -0.0230,
    tags: ['canal', 'graffiti'],
    blurb: "Hackney Wick and Fish Island. Old warehouses and the canal walls here hold some of London's densest graffiti. Walk the towpath and the side streets off Wallis Road.",
  },
  {
    id: 'bowie',
    name: 'David Bowie Mural',
    area: 'Brixton',
    lat: 51.4626, lng: -0.1157,
    tags: ['portrait', 'tribute'],
    blurb: "You're facing the David Bowie mural by Jimmy C, opposite Brixton station. Bowie was born nearby in 1947. After he died in 2016 this wall became a shrine of flowers and messages. The mural is now protected behind a clear screen.",
  },  // ---- More of London (positions checked against OpenStreetMap) ----
  {
    id: 'nuclear-dawn',
    name: 'Nuclear Dawn',
    area: 'Brixton',
    lat: 51.4619, lng: -0.1113,
    tags: ['mural', 'classic'],
    blurb: "This is Nuclear Dawn, painted by Brian Barnes with Dale McCray in 1981, at the height of Cold War fears. A giant skeleton in a cape strides over London as a mushroom cloud rises. It's one of the best-known of the community murals that made Brixton famous.",
  },
  {
    id: 'stockwell-mural',
    name: 'Stockwell Memorial Mural',
    area: 'Stockwell',
    lat: 51.4731, lng: -0.1221,
    tags: ['mural', 'history'],
    blurb: "The mural around the Stockwell war memorial was painted by Brian Barnes and Myra Harris in 2001. It honours Violette Szabo, a local resident who became a Second World War secret agent, alongside scenes from Stockwell's history.",
  },
  {
    id: 'hokusai-wave',
    name: 'The Great Wave, Camberwell',
    area: 'Camberwell',
    lat: 51.4707, lng: -0.0933,
    tags: ['mural'],
    blurb: "Dominic Swords painted this London version of Hokusai's Great Wave in 1997. Look for how the famous Japanese print has been reworked for a South London wall.",
  },
  {
    id: 'peckham-peace-wall',
    name: 'Peckham Peace Wall',
    area: 'Peckham',
    lat: 51.4737, lng: -0.0699,
    tags: ['public art', 'community'],
    blurb: "After the 2011 riots, people covered the boarded-up shop fronts on Rye Lane with thousands of Post-it notes saying what they loved about Peckham. The Peace Wall turns those messages into a permanent artwork. Get close and read a few.",
  },
  {
    id: 'choose-your-weapon',
    name: 'Banksy, "Choose Your Weapon"',
    area: 'Bermondsey',
    lat: 51.4953, lng: -0.0769,
    tags: ['Banksy', 'stencil'],
    blurb: "Banksy painted Choose Your Weapon here in 2010: a hooded figure holding the lead of a barking dog drawn in the style of Keith Haring, a nod to the New York artist. It has faded and been tagged over the years, so look closely.",
  },
  {
    id: 'cable-street',
    name: 'Cable Street Mural',
    area: 'Shadwell',
    lat: 51.5109, lng: -0.0586,
    tags: ['mural', 'history'],
    blurb: "This huge mural on the side of St George's Town Hall remembers the Battle of Cable Street on 4 October 1936, when East Enders blocked Oswald Mosley's British Union of Fascists from marching through. It was painted by Dave Binnington, Paul Butler, Ray Walker and Desmond Rochfort and finished in 1983.",
  },
  {
    id: 'hitchcock-mosaics',
    name: 'Hitchcock Mosaics',
    area: 'Leytonstone',
    lat: 51.5683, lng: 0.0085,
    tags: ['mosaics', 'film'],
    blurb: "Alfred Hitchcock was born in Leytonstone in 1899. The mosaics in the passageway at Leytonstone station tell his life and films, from The Birds to Psycho. See how many you can name.",
  },
  {
    id: 'wood-street-walls',
    name: 'Wood Street Walls',
    area: 'Walthamstow',
    lat: 51.5830, lng: -0.0280,
    tags: ['murals', 'community'],
    blurb: "Wood Street Walls is a Walthamstow community art project that has filled E17 with murals. Look out for pieces by ATM, who paints Britain's birds, especially endangered ones, at huge scale.",
  },
  {
    id: 'trellick-hof',
    name: 'Trellick Hall of Fame',
    area: 'North Kensington',
    lat: 51.5233, lng: -0.2052,
    tags: ['graffiti', 'hall of fame'],
    blurb: "In the shadow of Erno Goldfinger's Trellick Tower, these walls are a graffiti hall of fame where writers come to paint big, colourful pieces. They change all the time, so every visit is different.",
  },
  {
    id: 'stik-holding-hands',
    name: 'Stik, "Holding Hands"',
    area: 'Hoxton',
    lat: 51.5276, lng: -0.0812,
    tags: ['Stik', 'sculpture'],
    blurb: "Stik, famous for his simple stick figures, made this Holding Hands sculpture in 2020. With just two dots and a line he gives his figures a lot of feeling. Stik began painting on the streets of Hackney and Shoreditch.",
  },
  {
    id: 'hydra-towers',
    name: 'Phlegm, "Hydra Towers"',
    area: 'Hackney',
    lat: 51.5311, lng: -0.0666,
    tags: ['mural'],
    blurb: "This is Hydra Towers by Phlegm, a Sheffield artist known for his detailed black and white worlds of strange towers, machines and creatures. Take a minute to follow the little figures around the wall.",
  },
  {
    id: 'stik-haggerston',
    name: 'Stik mural, Haggerston',
    area: 'Haggerston',
    lat: 51.5382, lng: -0.0706,
    tags: ['Stik', 'mural'],
    blurb: "Stik painted this 14 metre high mural in 2012, commissioned by local residents. Stik's figures are simple, but where they stand and who they hold hands with often says something about the neighbourhood.",
  },
];

window.TOURS = [
  {
    id: 'shoreditch',
    name: 'Shoreditch Loop',
    desc: 'Brick Lane to Whitecross St · about 2.5 km',
    stops: ['hanbury-street', 'brick-lane', 'redchurch', 'village-underground', 'rivington', 'whitecross'],
  },
  {
    id: 'southbank',
    name: 'South Bank',
    desc: 'Leake Street tunnel and the Undercroft · about 1 km',
    stops: ['leake-street', 'undercroft'],
  },
  {
    id: 'camden',
    name: 'Camden',
    desc: 'Amy Winehouse mural to Camden Lock · about 1 km',
    stops: ['amy-winehouse', 'camden-lock'],
  },
  {
    id: 'brixton',
    name: 'Brixton & Stockwell',
    desc: 'Bowie, Nuclear Dawn and the Stockwell mural · about 2.5 km',
    stops: ['bowie', 'nuclear-dawn', 'stockwell-mural'],
  },
  {
    id: 'hoxton',
    name: 'Hoxton to Haggerston',
    desc: 'Stik, Phlegm and more Stik · about 2.5 km',
    stops: ['stik-holding-hands', 'hydra-towers', 'stik-haggerston'],
  },
  {
    id: 'peckham',
    name: 'Camberwell to Peckham',
    desc: 'The Great Wave to the Peace Wall · about 2 km',
    stops: ['hokusai-wave', 'peckham-peace-wall'],
  },
];

// Simulated start points for demo mode (nearest station to the first stop).
window.DEMO_STARTS = [
  { name: 'Liverpool Street', lat: 51.5178, lng: -0.0823 },
  { name: 'Waterloo', lat: 51.5031, lng: -0.1132 },
  { name: 'Camden Town', lat: 51.5392, lng: -0.1426 },
  { name: 'Brixton Village', lat: 51.4606, lng: -0.1118 },
  { name: 'Bond Street', lat: 51.5142, lng: -0.1494 },
  { name: 'Hackney Wick', lat: 51.5434, lng: -0.0247 },
  { name: 'Barbican', lat: 51.5204, lng: -0.0979 },
  { name: 'Old Street', lat: 51.5258, lng: -0.0875 },
  { name: 'Stockwell', lat: 51.4723, lng: -0.1229 },
  { name: 'Denmark Hill', lat: 51.4682, lng: -0.0892 },
  { name: 'Peckham Rye', lat: 51.4700, lng: -0.0694 },
  { name: 'Bermondsey', lat: 51.4979, lng: -0.0637 },
  { name: 'Shadwell', lat: 51.5113, lng: -0.0570 },
  { name: 'Leytonstone', lat: 51.5683, lng: 0.0083 },
  { name: 'Wood Street', lat: 51.5866, lng: -0.0024 },
  { name: 'Westbourne Park', lat: 51.5210, lng: -0.2011 },
  { name: 'Haggerston', lat: 51.5387, lng: -0.0756 },
];
